#- include_vars: ../../../../whis-platform/inventory/group_vars/local/vault

- name:          Upgrade all packages before docker and k8s
  yum:           
    name: "*"
    state: latest

- name: install docker dependencies
  become: yes
  yum:
    name:        ['yum-utils','device-mapper-persistent-data','lvm2','policycoreutils-python','python-pip','python-docker-py','git']
    state:       present
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

- name: install kubeadm dependencies
  become: yes
  yum:
    name:        ['ebtables', 'ethtool']
    state:       present
  when:
    - ansible_os_family == "RedHat"
    - (ansible_distribution == "RedHat" or ansible_distribution == "CentOS")

 
## TODO: @ebasso need investigation 
#- name: Add Artifactory repo
#  yum_repository:
#    name: Artifactory
#    description: Artifactory taas private repo
#    baseurl: https://{{docker_registry_username| trim| urlencode()}}:{{docker_registry_password| trim}}@na.artifactory.swg-devops.com/artifactory/wh-imaging-prereqs-rpm-local/
#    gpgcheck: no
#  when: setup=="private"

- name: Add docker-ce-stable public repo
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: yes
  when: setup=="public"

- name: Add kubernetes public repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch"
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    gpgcheck: yes
  when: setup=="public"

- name: Add docker-ce-stable private repo
  yum_repository:
    name: docker-ce
    description: docker-ce stable repo
    baseurl: "{{ docker_repo }}/centos/7/$basearch/stable"
    gpgkey:  "{{ docker_repo }}/centos/gpg"
    gpgcheck: yes
    enabled: yes
  when: setup=="private"

- name: Add kubernetes private repo
  yum_repository:
    name: kubernetes
    description: Kubernetes repo
    baseurl: "{{ kubernetes_repo }}/yum/repos/kubernetes-el7-$basearch"
    gpgkey: "{{ kubernetes_repo }}/yum/doc/yum-key.gpg {{ kubernetes_repo }}/yum/doc/rpm-package-key.gpg"
    gpgcheck: yes
    enabled: yes
  when: setup=="private"