#- include_vars: ../../../../whis-platform/inventory/group_vars/local/vault

- name:          Setup OS RedHat 
  include_tasks: setup-os-rh7.yml
  when:          ansible_distribution == "RedHat"
     
- name: Installs docker
  yum: 
    name: docker-ce-{{docker_version}} # docker in some distros
    state: installed     

# Remove docker-ce repo to not upgrade
- name: Remove docker-ce repo
  file: 
    path: "/etc/yum.repos.d/docker-ce.repo"
    state: absent
  ignore_errors: true

#- name: Install docker-py public repo
#  pip:
#    name: docker-py
#    extra_args: -i https://{{docker_registry_username| trim}}:{{docker_registry_password| trim}}@na.artifactory.swg-devops.com/artifactory/api/pypi/wh-imaging-pypi-local/simple
#  when: ( setup=="public" )
#
#- name: Install docker-py private repo
#  pip:
#    name: docker-py
#    extra_args: --trusted-host {{ private_repo}}
#  when: ( setup=="private" )

- name:            Create directories
  file:            path={{ item }} state=directory mode=0755
  with_items:
    - "/etc/docker"

- name:            Configure docker daemon network
  template:
    src:           daemon.json.bip.j2
    dest:          /etc/docker/daemon.json

#- name: restart docker
#  systemd: 
#    name: docker 
#    state: restarted
#    daemon_reload: yes
#    enabled: yes

- name:            Configure docker device mapper
  template:
    src:           daemon.json.j2
    dest:          /etc/docker/daemon.json

- name: restart docker
  systemd: 
    name: docker 
    state: restarted
    daemon_reload: yes
    enabled: yes

## TODO: @ebasso need investigation 
#- name: Logging to private docker registry
#  docker_login:
#    registry: "{{ docker_registry }}"
#    username: "{{ docker_registry_username }}"
#    password: "{{ docker_registry_password }}"
#    reauthorize: yes