---
- name: get epel
  get_url:
    url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm
  when: ( setup=="public" )

- name: install epel
  become: yes
  yum: 
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present
  when: ( setup=="public" )

# TODO: @ebasso need investigation 
- name: Install container-selinux rpm from a remote repo
  yum:
    name: http://ns3.centos.org/7.3.1611/extras/x86_64/Packages/container-selinux-2.9-4.el7.noarch.rpm
    state: present
  when: ( setup=="public" )

- name: install container-selinux from taas repo
  become: yes
  yum:
    name: container-selinux-2.9-4.el7.noarch
    state: present
  when: ( setup=="public" )
  
# can be needed in some systems
#  - name: Enable extra repos
#   command: subscription-manager repos --enable=rhel-7-server-extras-rpms